### ISSUE TITLE
[BUG] TuiValidatorDirective keeps validating even when destroyed

### ISSUE THREAD

**Issue by dev054** [taiga-family/taiga-ui#227]
# 🐞 Bug report

### Description
TuiValidatorDirective keeps validating even when destroyed.

### Reproduction

https://stackblitz.com/edit/taiga-dynamic-validation-9jqxvg

You can see the actual behavior in this record below. Basically, the use case is that I have conditional validation **and** the field is shown based on another value.

https://user-images.githubusercontent.com/28629080/108006673-e0ccbd80-6fda-11eb-96a3-4b6f30c7bf7a.mov

### Expected behavior
I'd expect the error not be there when the `<input [tuiValidator]="...">` gets destroyed.

### Versions

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Angular11
-   Package [e.g. @taiga-ui/cdk@2.0.0]

**Comment by waterplea** [comment]
Hi @dev054.

That's an issue with Angular, or rather the design limitation. Directive is provided through DI so there's no way to change anything once it is created. However, we replace the validation function with an empty validator in `ngOnDestroy` so your form control will not be invalid after the directive is destroyed. You see the error because validity state of the control has not been updated. I suggest you add `updateValueAndValidity` somewhere in your code where you hide the directive. We cannot be sure that we have access to control (directive can be above the actual control in the DI tree) and we cannot be sure that people want to retrigger validation in that case, so it's best to handle this locally.

**Comment by dev054** [comment]
Hey, thanks for the quick reply. I've workarounded this. Btw, is there any way that I can pass multiple validators to it? If not, should I open another ticket for it?

**Comment by waterplea** [comment]
You can use built-in composition from Angular:
https://angular.io/api/forms/Validators#compose
