### ISSUE TITLE
🚀 - Dont allow to select disabled dates in calendar

### ISSUE THREAD

**Issue by sakuranasty** [taiga-family/taiga-ui#3708]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core, addon-mobile

### Description

Currently there is an opportunity to pass disabledItemHandler, but it is possible to select disabled dates, if these dates are betwee two awailable dates.

Example:
![image](https://user-images.githubusercontent.com/34821835/219650969-7cb716f1-2f29-4ad8-933d-8d8500b75214.png)

Please add this feature to version 2.x

**Comment by p-ivannikov** [comment]
I will take it

**Comment by waterplea** [comment]
Had to rollback the change due to performance. Reopening

**Comment by splincode** [comment]
@p-ivannikov fyi

**Comment by waterplea** [comment]
I'm closing this as working as intended. Selection of dates should always be paired with a validator because in InputDateRange a user can manually type in a range with disabled dates inside and there's nothing we can do about it, other than invalidate the control. Since disabling dates is done through predicate to allow for rules/repeated dates, rather than an array of disabled dates – it is techincally very taxing to go over each day in an attempted range to check if it is not disabled. The benefits of adding this is minimal while technical and performance challenges are great, therefore closing this as not planned.
