### ISSUE TITLE
🐞 - Changing tabs content breaks active tab

### ISSUE THREAD

**Issue by evantrimboli** [taiga-family/taiga-ui#4189]
### Playground Link

https://stackblitz.com/edit/angular-ebr4z6

### Description

In the attached example:

- Open the example, note that the 'A' tab is highlighted as being active.
- Press the "change tabs" button.
- The tabs change, however 'D' is missing the active indicator.

### Angular version

12.2.17

### Taiga UI version

3.24.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Well, technically that's a different tab, that was not activated, but I get how you would expect `activeItemIndex` to sync it both ways. I'm not yet sure whether we should fix that, because that could get us into an invalid state with tabs that are activated through `routerLinkActive`. If we were to change this behavior we gotta make sure it works well with those too.

**Comment by evantrimboli** [comment]
Understood. Do you have any idea of how I could work around it for now?

**Comment by waterplea** [comment]
Oh, I see, it's not just that, you change `activeItemIndex` at the same time tabs change. That should work, looks like a race condition of sorts.

**Comment by waterplea** [comment]
> Understood. Do you have any idea of how I could work around it for now?

Maybe track by index or some non-changing id so that elements are not recreated?

**Comment by waterplea** [comment]
Seems to be fixed in v4, original stackblitz works as expected there with D being active
