### ISSUE TITLE
[BUG] Can't set dataTransfer in drag and drop directives

### ISSUE THREAD

**Issue by AnteaterKit** [taiga-family/taiga-ui#42]
Hello!

Can't understand how to set dataTransfer

I think setData must set in tuiDragStart, is it true?
But I can't get data in tuiDroppableDragOverChange

source code 
https://stackblitz.com/edit/taigacdk?file=src%2Fapp%2Fapp.component.html

**Comment by waterplea** [comment]
Drag directives are just wrappers around native events for `mousedown` -> `mousemove` -> `mouseup`. I suppose the name is confusing, because you might expect it to be wrapped around `drag` events. Typically we use it for resizing containers, dragging carousel and things like that. Drop directive is used for file input drag and drop (the input will be released in upcoming package). @MarsiBarsi what do you think, maybe we should rename it?

**Comment by MarsiBarsi** [comment]
Hey everyone 👋

Fine, I don't mind renaming, but I don't see a better name for this thing right now. Do you have ideas?

**Comment by waterplea** [comment]
Since we already released 2.0 we cannot rename as it will be breaking change. @AnteaterKit wrote in the other issue that examples in code have cleared our drag-drop directives behavior for him so I believe we can close this issue now. If any questions will arise, a new issue can be opened, or perhaps a topic in Discussions section.
