### ISSUE TITLE
🚀 - `Axes` allows to add label for the end of axisX

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#4886]
### Description

See https://taiga-ui.dev/charts/axes/API?axisXLabels$=1
<img height="400" alt="Screenshot 2023-07-11 at 11 27 53" src="https://github.com/Tinkoff/taiga-ui/assets/35179038/47966737-19a6-4a08-8037-99fc0a592c9f">

**Proposed new API:**
```
[axisXLabels]=[
    '', // first label
    '25%',
    '50%',
    '75%',
    '', // last label
]
```
<img height="400" alt="Screenshot 2023-07-11 at 11 27 53" src="https://github.com/Tinkoff/taiga-ui/assets/35179038/e542c510-3639-4fb7-a7bc-024a419f1b08">

**Comment by nsbarsukov** [comment]
<img width="650" alt="example" src="https://github.com/Tinkoff/taiga-ui/assets/35179038/af6eeee2-20f8-4520-99bc-7d66783b8a04">

**Comment by Drogenix** [comment]
@waterplea Can i try to write this? :)
 If i understand well, we just need to move the last label next to the axis end?

**Comment by waterplea** [comment]
> @waterplea Can i try to implement this? :)
>  If i understand well, we just need to move the last label next to the axis end?

Sure, go ahead. We also need the first label right next to the vertical axis as in the screenshot above. We just need to make sure we do not introduce breaking change. Typically, we do this by adding a `new` attribute which would enable the new behavior. I think this can even be done with just the CSS based on that attribute, but I didn't look closely.

**Comment by Drogenix** [comment]
> Sure, go ahead. We also need the first label right next to the vertical axis as in the screenshot above.

So this is what we want to get? We have 3 vertical lines, and 4 axisXLabels.

![image](https://github.com/taiga-family/taiga-ui/assets/101005283/427171fc-b867-4aac-878b-1ab434708d52)

I had to increase the x labels top padding (which created by :before element) because the first one is too close to y label:

![image](https://github.com/taiga-family/taiga-ui/assets/101005283/729fab9a-d513-47ff-ada8-b3bbac653eea)
