### ISSUE TITLE
🐞 - `InputNumber` ignores native attribute `maxlength`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#5058]
### Playground Link

https://stackblitz.com/edit/tui-input-number-maxlength-bug

### Description

```html
<tui-input-number>
    <input tuiTextfield maxlength="7" />
</tui-input-number>
```

Why?
https://github.com/Tinkoff/taiga-ui/blob/fe99d1377203508e01834f6acf3785885ecd20c6/projects/kit/components/input-number/input-number.directive.ts#L29

### Angular version

any

### Taiga UI version

3.39.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by 40oleg** [comment]
May I take this one?

**Comment by waterplea** [comment]
> May I take this one?

Yes, go ahead.

**Comment by 40oleg** [comment]
There is a problem.
Does native maxlength attribute have to count non-digit symbols like thousandSeparator?
e.g. "123 456" has length 6 or 7?
![image](https://github.com/taiga-family/taiga-ui/assets/60510512/cef64352-1705-41d0-ba0a-719c47c20ad0)
On picture above I set maxlength=7 but because of the space-symbol I can't type the seventh digit.
Is this behavior normal or not?

**Comment by 40oleg** [comment]
@waterplea @nsbarsukov  What do you think?

**Comment by nsbarsukov** [comment]
> Does native maxlength attribute have to count non-digit symbols like thousandSeparator?

I think that `maxlength attribute` should count any character (digits and non-digits).
For example, `maxlength=7` should allow to insert 6 digits and 1 space between them.

**Comment by splincode** [comment]
also `-123 456` is `maxlength=8`
