### ISSUE TITLE
🐞 - Issue with dropdown at the bottom of the page

### ISSUE THREAD

**Issue by KimAlexander** [taiga-family/taiga-ui#5928]
### Playground Link

https://stackblitz.com/edit/angular-d2zgt1-fiwkx9?file=src%2Fapp%2Fapp.component.html

### Description

1. Уменьшить окно браузера, чтобы появилась вертикальная прокрутка  
2. Кликнуть по меню в последней строке 
3. Пункты меню скрываются 

https://github.com/taiga-family/taiga-ui/assets/9423333/abb1c901-ef39-40c7-9311-56fb4f07d910

### Angular version

12.2.17

### Taiga UI version

3.53.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

**Comment by Drogenix** [comment]
@waterplea Can i try to work on this? Also, where should I look at, maybe you know any possible reasons of this behaviour?

**Comment by waterplea** [comment]
@Drogenix you can if you want, the issue is somewhere here probably:
https://github.com/taiga-family/taiga-ui/blob/main/projects/core/directives/dropdown/dropdown-position.directive.ts#L27
https://github.com/taiga-family/taiga-ui/blob/main/projects/core/directives/dropdown/dropdown.component.ts#L122

Also this one is somewhere close: https://github.com/taiga-family/taiga-ui/issues/6415
