### ISSUE TITLE
🐞 - scrolls overlap each other

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#7075]
### Playground Link

https://business.tinkoff.ru/

### Description

It turns out that when there are many applications on the page, the scrolls overlap each other

<img width="445" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/37ce46a1-5de0-44cf-99dd-ab71e359bb40">
<img width="543" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/1206659b-96d2-4108-8e7d-2ff12c7a4021">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
People can hide those scrolls by using CSS: `.not-main-app tui-root > tui-scroll-controls { display: none; }`, I don't think we should do anything more here, because each app most likely does not know it's not the only one and the orchestrator does not have access to `tui-root` of child app to set some input. Maybe we can add some DI token to abstract away knowledge of internal structure of `tui-root > tui-scroll-controls`, but I don't think it's worth it, at least for now.
