### ISSUE TITLE
🐞 - `Tabs` underline issue when removing a tab

### ISSUE THREAD

**Issue by gennadiipetrov** [taiga-family/taiga-ui#7122]
### Playground Link

https://stackblitz.com/edit/angular-yiwrcu?file=src%2Fapp%2Fapp.component.html

### Description

see stackblitz sample

for repeat
1) after 5 seconds 1 tab disappears (`Maps` tab)
2) underline disappears from `Call` tab (you can see from the color of the text that the tab is not active)
3) click on the button below to set activeIndex 
4) see that `Call` tab changes color (which means it becomes active)
5) but the underline does not appear

the underline may appear when you click on the tab or resize the window

### Angular version

17.2.2

### Taiga UI version

3.71.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Chiorufarewerin** [comment]
i will try it

**Comment by Chiorufarewerin** [comment]
This issue was already fixed in the 'main' branch:
https://stackblitz.com/edit/angular-khbcnp?file=src%2Fapp%2Fapp.template.html

As the issue described we need to click to the button in order to SET activeIndex. But this isn't true. Our activeIndex will stay 0. So this is a problem with rendering, and after clicking (or hovering) we trigger `ngAfterViewChecked`.

It was fixed here by setting `_active` state to a tab after next render:
https://github.com/taiga-family/taiga-ui/pull/7355

I'm not sure, but the underlining issue was probably fixed by making the underline through styles and setting them by `@HostListener('animationend')`. In the 3.x it uses the separate component `tui-underline`.
