### ISSUE TITLE
🐞 - DataList with single option has stuck focus

### ISSUE THREAD

**Issue by hzsenko** [taiga-family/taiga-ui#7199]
### Playground Link

https://stackblitz.com/edit/angular-e8369x?file=src%2Fapp%2Fapp.component.html

### Description

I have DataList with single tuiOption. If I focus on option, focus state will not disappear ever.

### Angular version

17.2.1

### Taiga UI version

3.74.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That's because you use a non-focusable dropdown host. It makes your dropdowns not keyboard accessible. When hovering an item it focuses the item, when moving mouse away from the dropdown – it tries to focus the host, but in your case there's nothing to focus. Please use buttons, not non-interactive icons as dropdown hosts.
