### ISSUE TITLE
🐞 - `tuiTextfieldSize` is ignored

### ISSUE THREAD

**Issue by robingenz** [taiga-family/taiga-ui#8540]
### Playground Link

https://stackblitz.com/edit/angular-u3hssa-pnnbc2

### Description

It seems that `tuiTextfieldSize` is ignored. The font of the user input is always the same size:

![image](https://github.com/user-attachments/assets/18d17a5b-b125-4071-8552-9f3d641b0333)

I just copied the example from the [docs](https://taiga-ui.dev/components/input#sizes). Are any additional configurations necessary that are not documented?

### Angular version

17.0.0

### Taiga UI version

4.2.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Thank you for bringing this up. Looks like font-size is inherited inside input, but it is not set on the `tui-primitive-textfield` according to the size for small and medium sizes, only for large. And in the demo it was not visible because parent font size was small, like it should be for m and s textfield sizes. Would you like to make a PR? In this file font is only set for data-size="l":
https://github.com/taiga-family/taiga-ui/blob/main/projects/legacy/styles/mixins/textfield.less#L10

It should be `font: var(--tui-font-text-s);` for both.

Same for this file:
https://github.com/taiga-family/taiga-ui/blob/main/projects/legacy/styles/mixins/textfield.scss

**Comment by robingenz** [comment]
Thank you for your fast reply. Of course, give me a minute.
