### ISSUE TITLE
🐞 - `CardLarge` incorrect content padding

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#8916]
### Description

The docs state that `Normal` design should have `24/20` paddings and `Compact` `20/16`. In reality `Normal` has `24` on all sides, `Compact` has `20` on all sides.

![image](https://github.com/user-attachments/assets/cb30bec6-0752-4031-849c-207ec9b15085)

![image](https://github.com/user-attachments/assets/5f9ccec4-9882-470b-99c3-dccd9dcd2c8c)

### Sidenote

The code link also leads to `404` page.

### Angular version

18.2

### Taiga UI version

4.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
@waterplea 
The `CardLarge` directive also shows the clear drawbacks of `tuiWithStyles()` workaround to add styles to directives.
Following looks different inside and outside of `CardLarge` because of `CardLarge` leaking styles (no encapsulation):
```html
<label tuiLabel>
    <span tuiTitle>
        <span tuiSubtitle class="title">Foo</span>
        Bar
    </span>
</label>
```

**Comment by waterplea** [comment]
It's not "leaking", it's by design. `Title` is a fundamental atomic piece of title/subtitle pair. Many other components such as cards, cells, table, header etc. style it differently. Label and card apply secondary color to subtitle, for example. There's no way to both expose content to you, as a developer AND encapsulate styles so this is the middle ground that seems to be working great for us so far. A rather wide variety of layouts can be achieved out of the box with little to none styles tweaking:
https://taiga-ui.dev/layout/cell

As for paddings for the card — problem here is that vertical padding should be different depending on the content. For buttons, for example, both vertical and horizontal padding should be the same to look good. For the text, however, there has to be visual compensation. The specs shown it as smaller vertical padding, but I think when we implemented it we decided that it's easier to apply negative margins to compensate than the other way around, because sometimes it has to be in both directions:
![image](https://github.com/user-attachments/assets/374b328f-a346-49cb-a380-b160a4d7c73d)

It also looks much less terrible out of the box if text does not have that visual compensation, rather than button at the end of the card having different distance to the edges of the card:
![image](https://github.com/user-attachments/assets/b78562df-52e8-43a6-a936-3ee315dc8dc6)

If you have any suggestions as to how to handle this situation better — please share them. If not, than I'd say this issue is only about removing secondary padding number from the demo.

**Comment by hakimio** [comment]
- Most of the cards in my applications don't have buttons at the bottom, so the reduced padding makes sense. Anyway, I guess it's subjective and I get your point.
- To be honest, I don't get why the `card` directive should apply bold heading style to `title` inside `label[tuiLabel]` which is supposed to be styled by `tuiLabel`.

**Comment by waterplea** [comment]
Would you make a PR to add `font: var(--tui-font-text-ui-m);` to `[tuiTitle]` inside label so that it overrides the bold font applied by card? It makes sense for label to take precedence here as it is a lower level structure so it's more precise. Also duplicate `[tuiTitle]` selector there to increase specificity, otherwise they would have the same one and it would come down to what component was created first. And the second padding number should be removed from the demo. I'll add a label for external contributors if you're not up for it right now.
