### ISSUE TITLE
🚀 - `Textfield` option to disable `cleaner` using directive input

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#9100]
### Description

Right now it seems the only way to disable the `tui-textfield` cleaner is using the provider:
```ts
providers: [
    tuiTextfieldOptionsProvider({
        cleaner: signal(false)
    })
]
```

This is not a great solution when you want to disable `cleaner` for a single textfield in a form. It would be nice if `tuiTextfield` directive provided input to control the `cleaner`.

**Comment by waterplea** [comment]
No, there's `TuiTextfieldOptions` directive that allows you to do it same way you did before:
https://github.com/taiga-family/taiga-ui/blob/main/projects/core/components/textfield/textfield.options.ts#L41
It is used to set appearance, size and cleaner. You just need to put it on `tui-textfield`, not on `tuiTextfield`, since the cleaner is inside the wrapper, not in the actual `input` tag.

**Comment by hakimio** [comment]
When even options is a separate directive, it's not very discoverable. The options won't be auto-completed by the IDE on the `tui-textfield` and when [the docs](https://taiga-ui.dev/components/textfield) don't have `API` tab, how are you supposed to know about it without reading the source code?

**Comment by waterplea** [comment]
We are working on improving docs for exactly such cases, where a component can be extended with directives and host directives, such as appearance or icons. 

When you import `TuiTextfield` as a whole — it should auto import that directive too and add suggestions:

![image](https://github.com/user-attachments/assets/8972b0da-1888-4796-8b7a-a16ba0409509)

It's a separate directive because it can be applied to sections of the app as a whole. This thing hasn't really changed since v3.

**Comment by hakimio** [comment]
Even when the directive is imported, if you are just checking available `tui-textfield` options and you are not sure how the option could be named, you get a long list like the following with `tuiTextFieldCleaner` somewhere at the bottom of 100 items:

![image](https://github.com/user-attachments/assets/66a2809b-f118-473d-8bdf-4e235de1a56a)

Not great DX.
