### ISSUE TITLE
🐞 - `Textfield` changing `readOnly`/`invalid` not trigger change detection on API page

### ISSUE THREAD

**Issue by mdlufy** [taiga-family/taiga-ui#9389]
### Reproduction url

https://taiga-ui.dev/components/textfield/API/

### Description

1. Open https://taiga-ui.dev/components/textfield/API/
2. Try to change `readOnly` or `invalid` value
3. It updates only after click away

But it works correctly on stackblitz
https://stackblitz.com/edit/angular-ryaheg?file=src%2Fapp%2Fapp.template.html

### Taiga UI version

last

### Browser Used

Chrome

### OS Used

macOS

**Comment by nsbarsukov** [comment]
Updating `@Input()` props inside `TuiTextfieldBase` triggers setting new value for the following signals

https://github.com/taiga-family/taiga-ui/blob/8217c9030781b30ae6102f57dc4d13f64199f6c1/projects/core/components/textfield/textfield.directive.ts#L80-L81

https://github.com/taiga-family/taiga-ui/blob/8217c9030781b30ae6102f57dc4d13f64199f6c1/projects/core/components/textfield/textfield.directive.ts#L29

However, this `compute` is not recalculated before nearest CD
https://github.com/taiga-family/taiga-ui/blob/12e9a29436b309f5d7b2229249c1113b06a2ff3d/projects/core/directives/appearance/appearance.directive.ts#L47-L48

___

It is Angular bug.
It is reproducible in `v16`. It was fixed in `v17`.

Explore more:
* https://stackblitz.com/edit/tui-directive-binding-ng-16?devToolsHeight=33
* https://stackblitz.com/edit/tui-directive-binding-ng-17?devToolsHeight=33 

___

So, closing this issue. It will be solved automatically after update `demo`-application to `@angular/core@17`.
