### ISSUE TITLE
🚀 - `Aside` better customization options

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#9392]
### Description

Right now the `aside` component doesn't seem to be customizable:
- no way to change button size
- no way to manually control expanded state of `tui-aside-group`
- hardcoded values for width/padding
- has annoying hardcoded behavior where group dropdown closes every time you select an item
- hardcoded `dark` mode. If you want to have light sidebar, you have to resort to ugly `[attr.tuiTheme]="null"` hack
- hardcoded rounded corner (the `aside::before` style) which doesn't work well with all designs
- `tuiNavigationDrawer` has hardcoded icon, `dark` mode and top offset

Anyway, why don't you use the new component for the demo site navigation? Would be a good way to test it.

**Comment by waterplea** [comment]
This component is specifically designed for information heavy admin control panels we use internally for things like network management, error logs, support tickets, repositories etc. Kind of like GitLab interface. It is made with stricter specification that what we usually have, but we didn't want to keep it proprietary in case other people might also find it useful. There are no plans to make it more flexible at this point.

- You cannot change buttons size because the collapsed size is designed in a way that only that particular button size fits well
- Manual control of expanded state of `tui-aside-group` can be added, we do not need it at this point so if it's important to you — you can make a PR
- That ties to the button size, it is hardcoded so everything properly fits together. Seems like it would be possible to add `size` option to the overall navigation to account for that, but this is not something we need right now as this navigation is intended to take up as little space as possible.
- Group dropdown does not close automatically 🤔 There's a specific one item in the demo (`Fiction (will close menu)`) that closes it and the rest do not
- You can add `tuiTheme="light"`, it takes precedence over built in dark theme
- It is specifically made a pseudo element so that it's available for you to `display: none` without ::ng-deep
- Icon can be overridden with DI, drawer content is arbitrary, you can just add a `div` with `tuiTheme="light"` to override dark theme. Hardcoded `top` offset ties back to the same argument that sizes and paddings are predesigned and not intended to be customizable.

We do not use it for demo because we don't want our demo to look that tight, it's not data-heavy interface. Here's a little demo with some of the things you've mentioned customized:
https://stackblitz.com/edit/angular-ihqcbn

P.S. Colors in the dropdown from the sidebar are hardcoded for dark theme, I'll fix that.

**Comment by hakimio** [comment]
> Group dropdown does not close automatically 🤔

It does for me:

![navigation](https://github.com/user-attachments/assets/81a93f75-1ae0-4c4c-a7ed-57a143b4fa6a)

> You can add tuiTheme="light", it takes precedence over built in dark theme

Then the navigation's theme will not change when you change apps mode to dark. It will always stay in fixed "light" mode even when you change the rest of the app to "dark" mode. I want my navigation panel to adapt to application's theme. Like, for example, following dashboard demo: 
[DevExtreme Dashboard Demo](https://devexpress.github.io/devextreme-ui-template-gallery/material.blue.light.compact/angular/default/#/analytics-dashboard)

> It is specifically made a pseudo element so that it's available for you to display: none without ::ng-deep

Being pseudo element is fine, it's not fine that it's not configurable through component's inputs and you have to resort to CSS hacks.

> Icon can be overridden with DI

Where is this documented?

> Here's a little demo with some of the things you've mentioned customized

Thank you for taking the time to make a demo and answer my questions.

---

A couple of things I noticed while looking at the code:
- When you are using `tuiOption` directive on the navigation buttons is there any real need for `appearance="flat"`?
- Pretty much everywhere else you prefer lazy loaded components (including `tuiSidebar`), but for `tuiNavigationDrawer` you chose to make it eagerly loaded. Any particular reason for that?
https://github.com/taiga-family/taiga-ui/blob/5343993e7a2cd2a148941e1ed988fa6572b56823/projects/layout/components/navigation/drawer.component.ts#L56

**Comment by waterplea** [comment]
> It does for me:

Oh, I misunderstood you. I'll fix that.

> Then the navigation's theme will not change when you change apps mode to dark. It will always stay in fixed "light" 

Then use `[attr.tuiTheme]="dark() ? 'dark' : 'light'"` using `TUI_DARK_MODE`

> you have to resort to CSS hacks

It is not a hack, we intentionally simplify internal DOM across components so when you need something specific — you could to it by plain CSS without hacks. This is our strategy to make things easier to customize without trying to think of every possible way people would want to change things and making a flag for each one of them. That's a general approach of this library.

> Where is this documented?

Nowhere at this moment. Just a general rule you can keep in mind — our internal projects use different icon set so every icon in Taiga UI is customizable with DI. I'll add that example to the docs so people will see how it can be done.

> When you are using tuiOption directive on the navigation buttons is there any real need for appearance="flat"?

I'm not sure what you mean here. Appearance is exposed so it can be customized. I'll add that to example.

> Any particular reason for that?

For simplicity as well as for it being always there and not rebuilt when you open/close. This is less of a general use component than the rest of Taiga UI. Is that important to you here?

**Comment by hakimio** [comment]
> I'm not sure what you mean here. Appearance is exposed so it can be customized. I'll add that to example.

Specifically in the following code, I don't see why `appearance: 'flat'` is needed when you are already using `tuiOption` directive on the button:
https://github.com/taiga-family/taiga-ui/blob/5343993e7a2cd2a148941e1ed988fa6572b56823/projects/layout/components/navigation/aside.component.ts#L34

> For simplicity as well as for it being always there and not rebuilt when you open/close. This is less of a general use component than the rest of Taiga UI. Is that important to you here?

I wanted to use that feature for "mobile only" menu like you have in the demo app. Since my app is mostly used in desktop environments, rendering the menu twice on desktop doesn't make much sense to me.

**Comment by waterplea** [comment]
There's no `TuiOption` on `TuiAsideItem`, just an attribute as a hack for data-list to recognize them as options, I think we should drop that and make data-list not show "Nothing is found" if any button/link are inside.

I've made a PR that, I believe, addresses everything we discussed here that I believe should be addressed, including manual control of `AsideGroup` expansion.

**Comment by hakimio** [comment]
Thank you.

**Comment by hakimio** [comment]
@waterplea colors in the dropdown from the sidebar are still hardcoded to dark theme. It doesn't respect theme set on the `aside`.

**Comment by hakimio** [comment]
Sorry, it works when using `TuiThemeColorService` instead of just setting CSS var.
