### ISSUE TITLE
🐞 - value in the input is overlapped by a `tuiTextfieldPrefix` when scrolling

### ISSUE THREAD

**Issue by dzolotarova** [taiga-family/taiga-ui#9679]
### Reproduction url

https://stackblitz.com/edit/angular-fhtqky

### Description

If a value in an input that uses a prefix is long, the value in the input is overlapped by a `tuiTextfieldPrefix` when scrolling.

![Image](https://github.com/user-attachments/assets/07c4ffd0-4912-4a94-887a-2c43dffa452f)

### Taiga UI version

3.89.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
In our new inputs there will be no prefix and postfix elements, you can use Maskito for it. This issue will not be fixed for legacy inputs and v3, since the approach has changed. This ticket will be resolve by adding example how to use postfix (and not have it in the form control value) here:
https://taiga-ui.dev/components/textfield#mask
