### ISSUE TITLE
🐞 - Different keyboard behavior when focusing in dropdown

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#9837]
### Reproduction url

https://taiga-ui.dev/components/data-list#submenu

### Description

https://github.com/user-attachments/assets/812f708c-51d0-46d7-b2c3-47155a5ca3fc

### Taiga UI version

latest

### Browser Used

Safari

### OS Used

macOS

**Comment by waterplea** [comment]
Closing this as working as expected. This is because dumb Safari does not focus buttons on click unless you toggle checkbox in OS settings to do so. If you plan on using keyboard navigation — you have most likely already enabled the "sane" setting as opposed to default by UX genius engineers of Apple.

**Comment by splincode** [comment]
`If you plan on using keyboard navigation — you have most likely already enabled the "sane" setting as opposed to default by UX genius engineers of Apple` I didn't even know about this, thanks

![Image](https://github.com/user-attachments/assets/ea966642-889c-4913-bb41-98c6f0c388ff)

Do you mean that I should switch this toggle on myself?

**Comment by waterplea** [comment]
Yes, you need to enable "Keyboard navigation", by some inexplicable reason it is disabled by default.
